# CLI tools
brew "biome"
brew "colima"
brew "docker"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "go"
brew "nvm"
brew "pyenv"
brew "pyright"
brew "ruff"
brew "stow"
brew "tmux"
brew "tree"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

# GUI apps
cask "claude-code"
cask "font-liga-comic-mono"
cask "font-sf-mono-nerd-font-ligaturized"
cask "ghostty"
cask "mactex"
cask "obsidian"
cask "zed"
