set -g mouse on
setw -g automatic-rename off

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g renumber-windows on
set -g set-clipboard on
set -g status-position top
set -g default-terminal "${TERM}"
setw -g mode-keys vi
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

# Catppuccin mocha colors
set -g @thm_bg "#1e1e2e"
set -g @thm_fg "#cdd6f4"
set -g @thm_cyan "#89dceb"
set -g @thm_black "#181825"
set -g @thm_gray "#313244"
set -g @thm_magenta "#cba6f7"
set -g @thm_pink "#f5c2e7"
set -g @thm_red "#f38ba8"
set -g @thm_green "#a6e3a1"
set -g @thm_yellow "#f9e2af"
set -g @thm_blue "#89b4fa"
set -g @thm_orange "#fab387"
set -g @thm_black4 "#585b70"

set -g status-style "bg=default,fg=#{@thm_fg}"
set -g status-left-length 100
set -g status-right-length 100

set -g status-left "#[fg=#{@thm_green},bg=default]#[fg=#{@thm_black},bg=#{@thm_green},bold]  #S #[fg=#{@thm_green},bg=default] "
set -g window-status-separator ""
set -g window-status-format "#[fg=#{@thm_blue},bg=default]#[fg=#{@thm_black},bg=#{@thm_blue}] #W #I #[fg=#{@thm_blue},bg=default] "
set -g window-status-current-format "#[fg=#{@thm_magenta},bg=default]#[fg=#{@thm_black},bg=#{@thm_magenta},bold] #W #I #[fg=#{@thm_magenta},bg=default] "
set -g status-right "#[fg=#{@thm_cyan},bg=default]#[fg=#{@thm_black},bg=#{@thm_cyan}]  #(whoami) #[fg=#{@thm_cyan},bg=default] #[fg=#{@thm_blue},bg=default]#[fg=#{@thm_black},bg=#{@thm_blue}]  %H:%M #[fg=#{@thm_blue},bg=default]"

# TPM
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
run '~/.tmux/plugins/tpm/tpm'
